# k8s/flask-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-auction
  namespace: auction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-auction
  template:
    metadata:
      labels:
        app: flask-auction
    spec:
      containers:
        - name: flask
          image: flask-auction:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis.auction.svc.cluster.local
