apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: auction
spec:
  type: NodePort
  selector:
    app: flask-auction
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
